#!/bin/bash

CURRENT_BRANCH=$(git branch &>/dev/null; if [ $? -eq 0 ]; then echo "$(git branch | grep '^*' |sed s/\*\ //)"; fi)
HERE=$(pwd)
cd ./$(git rev-parse --show-cdup)
CURRENT_ROOT=$(pwd)
NEW_ROOT=$CURRENT_ROOT-$1
git checkout -b $1 || exit 1
cd ..
git clone --shared --branch $1 ${CURRENT_ROOT}/.git ${NEW_ROOT}
cd $HERE
git checkout ${CURRENT_BRANCH}
echo "Make changes in ${NEW_ROOT}, commit, then push (to origin)".

exit