#!/bin/bash

CURRENT_BRANCH=$(git branch &>/dev/null; if [ $? -eq 0 ]; then echo "$(git branch | grep '^*' |sed s/\*\ //)"; fi)
HERE=$(pwd)
NEW=$HERE-$1
git checkout -b $1
cd ..
git clone --branch $1 ${HERE}/.git ${NEW}
cd $HERE
git checkout ${CURRENT_BRANCH}
echo "Make changes in ${NEW}, commit, then push (to origin)".

exit